### ISSUE TITLE
Hints with simulation configuration

### ISSUE THREAD

**Issue by ericchaves** [acesinc/json-data-generator#14]
Hi Folks,

I'd like to use json-data-generator to generate events that mimics users interacting with a content application. Due to the nature of the application however there are a few requirements to be met:

1-content has an ordered structure of 1-cover x N items that impose a given navigation condition (ie, in order to see the 2nd item of a given content you must see the cover and 1st item).
2-I need to simulate multiple users navigating at the same time (or in a given interval) 

I noticed on the readme that there is some kind of cursor or references, but it was not  clear how can I use them.

Can you give some directions on how to build those events?

Thanks in advance

**Comment by andrewserff** [comment]
From what it sounds like, you want to generate a number of events and generate them in order.  This is definitely doable with this framework.  You can also simulate multiple users.  If you take a look at the [`exampleWorkflow.js`](https://github.com/acesinc/json-data-generator/blob/master/src/dist/conf/exampleWorkflow.json) in the `src/dist/conf` directory, you see that this workflow simulates a person entering a building, logging into a computer, performing some random actions, and then logging out and leaving. The events are generated in the order they are placed in the config's `steps` property. 

To have multiple users you would create multiple Workflows (if you wanted them to be different) and then list them in the Sim Config workflows.  Then both of those workflows will run when the simulation starts.  

You mentioned a "cursor" and the is a type of cursor, but only within an event.  See the `this.propName` and `cur.propName` sections of the documentation.  These allow you to reference already generated values, but only within the current json event being generated.  You can't currently reference values within a previously generated event unfortunately.  

Hope this helps! If not, let me know.

**Comment by ericchaves** [comment]
Hi Andrew, thanks for the promptly reply. In the exempleWorkflow.js, the user enters the build, logs in, performs a single action and leave. 

how would you do have a random number of actions for a given step instead of a single action?  is, user enters build (1 step/1 event), logs in (1 step/1 event), performs a random number of actions (1 step/N events)? Is it possible?

Thanks again for the help

**Comment by andrewserff** [comment]
Yes, that's possible. Check out the Step's `duration` config option in the documentation.  It gives you the different ways to set it for what you want.

**Comment by ericchaves** [comment]
Hi Andrew,

On last question, is it possible to format dates and numbers? I tried date().toString('yyyy/MM/dd') but it has no effect.

If you allow me a feature suggestion, it would be great to have a put/get function to add into a kind of session object, allowing us to share some values in running workflow. Something like:
```
steps:[
{config:[{ "birthdate": "put(date(),'birthday')"},{...},{...}]},
{config:[{"userBirthdate":"get('birthday')"}]}]
```

**Comment by andrewserff** [comment]
Unfortunately, there is no way to format a date. Also, as you noticed, there is no type of session/context.  Both are good ideas though!  Feel free to submit them both as feature requests.  If you have time to implement either, we always welcome pull requests!

**Comment by andrewserff** [comment]
Closing based on lack of activity. If there is still an issue, please let me know.

**Comment by andrewserff** [comment]
The idea of state was referenced here and I'm trying to track those request in #28
