### ISSUE TITLE
support: question

### ISSUE THREAD

**Issue by jonashartwig** [acesinc/json-data-generator#27]
Hi, I have a a workflow containing one step with three config elements. It should generate events which are linked via id. Is there a way to use a value from message 1 from config in same config for message 2?

regards

**Comment by andrewserff** [comment]
Unfortunately right now, state only exists within a single event. So you can only reference previously generated properties in a single event, not across events or workflows.

**Comment by andrewserff** [comment]
I'm closing this in favor of issue #28 where I'll track these requests.
