### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by guenhter** [acesinc/json-data-generator#33]
Hi,

the last released version is from May 25, 2016
Since then, a lot new features were added (appreciate that). 
Don't you plan to make periodic releases any more, because they are quite nice to use in e.g. the test automation by just downloading it instead of cloning+building.

**Comment by andrewserff** [comment]
Thanks for the push.  I just released [v1.3.0](https://github.com/acesinc/json-data-generator/releases/tag/json-data-generator-1.3.0). Enjoy!

**Comment by guenhter** [comment]
Thx!
