### ISSUE TITLE
Library not published in maven repositories

### ISSUE THREAD

**Issue by nmargaritis** [acesinc/json-data-generator#37]
Hi there, 😸 

I noticed that this project is not published in maven repositories. Is there a reason you have not published this project so far?

Best, Nick.

**Comment by andrewserff** [comment]
`json-data-generator` is available in maven. See here: http://search.maven.org/#artifactdetails%7Cnet.acesinc.data%7Cjson-data-generator

**Comment by nmargaritis** [comment]
Thanks, I was trying with **1.3.1-SNAPSHOT** as suggested by the project's pom. It appears that 1.3.0 is available.
```
<dependency>
    <groupId>net.acesinc.data</groupId>
    <artifactId>json-data-generator</artifactId>
    <version>1.3.0</version>
</dependency>
```
