### ISSUE TITLE
Generate JSON web server logs

### ISSUE THREAD

**Issue by JocaPC** [acesinc/json-data-generator#39]
Hi,

I have successfully used your tool to generate fake log entries that simulate logs generate by some web server. This includes header/response data  URL, duration, exceptions, etc.

I would like to share my workflow/config because I believe that others might be interested to use it or enhance it.
I have submitted the files in pull request #38 

Regards,
Jovan

**Comment by jovanpop-msft** [comment]
Hi,
Would you review the PR and accept the change if it is fine?
Regards,
Jovan

**Comment by andrewserff** [comment]
Just merged it.  Thanks!
