### ISSUE TITLE
Error : Cannot find symbol

### ISSUE THREAD

**Issue by dnellurvalappil** [acesinc/json-data-generator#7]
![error](https://cloud.githubusercontent.com/assets/17819928/15954488/73ea564e-2e8c-11e6-82b3-fe1029038d5d.PNG)

I am getting this error. Couldn't find much help on this.

**Comment by andrewserff** [comment]
Are you building with Java 1.8? getOrDefault was added in 1.8, so it won't compile in anything older.

**Comment by dnellurvalappil** [comment]
No, its Java 1.7

**Comment by dnellurvalappil** [comment]
Thanks. I will try with Java 1.8

**Comment by dnellurvalappil** [comment]
![maven_build_error](https://cloud.githubusercontent.com/assets/17819928/16086010/df052914-32d2-11e6-970d-5caa56ec352b.PNG)

This time I tried with java 1.8, but still getting few errors. PFA for the screeshot.

**Comment by dnellurvalappil** [comment]
output of   mvn -v 
![maven_prop](https://cloud.githubusercontent.com/assets/17819928/16086144/5bce621c-32d3-11e6-8b70-52a0aa7dd987.PNG)

**Comment by dnellurvalappil** [comment]
got it now !

**Comment by andrewserff** [comment]
Looks like you got it working, so I'm going to close this issue.
